### ISSUE TITLE
Add type annotation support.

### ISSUE THREAD

**Issue by trim21** [05bit/peewee-async#125] opened 2019-05-21 02:44 UTC
A example:
```python
from typing import TypeVar, Type

T = TypeVar('T')

class Manager:
    async def get(self, source_: Type[T], *args, **kwargs) -> T:
        pass
```

**Comment by kalombos** [comment] 2023-05-16 06:14
@trim21 thank you for your proposal i think we need mypy checker in CI if we add type annotation in the code

**Comment by kalombos** [comment] 2024-05-12 16:40
Closed as duplicate of #224

**Closed by kalombos** 2024-05-12 16:40 UTC
